# template for bootstrapping gloo

---
#system namespace
apiVersion: v1
kind: Namespace
metadata:
  name: gloo-system
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: upstreams.gloo.solo.io
spec:
  group: gloo.solo.io
  names:
    kind: Upstream
    listKind: UpstreamList
    plural: upstreams
    singular: upstream
  scope: Namespaced
  version: v1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: virtualhosts.gloo.solo.io
spec:
  group: gloo.solo.io
  names:
    kind: VirtualHost
    listKind: VirtualHostList
    plural: virtualhosts
    singular: virtualhost
  scope: Namespaced
  version: v1
---
#rbac for gloo
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gloo-role
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["gloo.solo.io/v1"]
  resources: ["upstreams", "virtualhosts"]
  verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gloo-cluster-admin-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: gloo-system
roleRef:
  kind: ClusterRole
  name: gloo-role
  apiGroup: rbac.authorization.k8s.io
---
# Source: gloo/templates/ingress-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-config
  namespace: gloo-system
data:
  envoy.yaml: |
    node:
      cluster: ingress
      id: NODE_ID_PLACE_HOLDER
    static_resources:
      clusters:
      - name: xds_cluster
        connect_timeout: 5.000s
        hosts:
        - socket_address:
            address: gloo
            port_value: 8081
        http2_protocol_options: {}
        type: STRICT_DNS
    dynamic_resources:
      ads_config:
        api_type: GRPC
        cluster_names:
        - xds_cluster
      cds_config:
        ads: {}
      lds_config:
        ads: {}
    admin:
      access_log_path: /dev/null
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 19000

---
# Source: gloo/templates/fd-svc.yaml

apiVersion: v1
kind: Service
metadata:
  name: function-discovery
  namespace: gloo-system
  labels:
    gloo: function-discovery
spec:
  ports:
  - port: 8080
    protocol: TCP
    name: http
  selector:
    gloo: function-discovery

---
# Source: gloo/templates/gloo-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: gloo
  namespace: gloo-system
  labels:
    gloo: control-plane
spec:
  type: NodePort
  ports:
    - port: 8081
      protocol: TCP
      name: http
  selector:
    gloo: control-plane
---
# Source: gloo/templates/ingress-svc.yaml
# GW
apiVersion: v1
kind: Service
metadata:
  name: ingress
  namespace: gloo-system
  labels:
    gloo: ingress
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      name: http
    - port: 8443
      protocol: TCP
      name: https
    - port: 19000
      protocol: TCP
      name: admin
  selector:
    gloo: ingress
---
# Source: gloo/templates/fd-deployment.yaml

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: function-discovery
  namespace: gloo-system
  labels:
    gloo: function-discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      gloo: function-discovery
  template:
    metadata:
      labels:
        gloo: function-discovery
    spec:
      containers:
      - name: function-discovery
        image: "soloio/gloo-function-discovery:5.158034e+06"
        imagePullPolicy: IfNotPresent
        env:
        - name: GRPC_TRACE
          value: "all"
        - name: DEBUG
          value: "1"
        command: ["/gloo-function-discovery"]
        args:
        - "--storage.type=kube"
        - "--storage.refreshrate=30m"
        - "--secrets.type=kube"
        - "--secrets.refreshrate=30m"
        - "--kube.namespace=gloo-system"

---
# Source: gloo/templates/gloo-deployment.yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: gloo
  namespace: gloo-system
  labels:
    gloo: control-plane
spec:
  replicas: 1
  selector:
    matchLabels:
      gloo: control-plane
  template:
    metadata:
      labels:
        gloo: control-plane
    spec:
      containers:
      - name: gloo
        image: "soloio/gloo:v0.1.6-111"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
          name: http
        env:
        - name: GRPC_TRACE
          value: "all"
        - name: DEBUG
          value: "1"
        command: ["/gloo"]
        args:
        - "--storage.type=kube"
        - "--storage.refreshrate=1m"
        - "--secrets.type=kube"
        - "--secrets.refreshrate=1m"
        - "--xds.port=8081"
        - "--kube.namespace=gloo-system" 
---
# Source: gloo/templates/ingress-deployment.yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: ingress 
  namespace: gloo-system
  labels:
    gloo: ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      gloo: ingress
  template:
    metadata:
      labels:
        gloo: ingress
    spec:
      initContainers:
      - name: assignnodeid
        image: busybox
        command:
        - sed
        - s/NODE_ID_PLACE_HOLDER/$(POD_NAME).$(POD_NAMESPACE)/
        - -i
        - "/config/envoy.yaml"
        volumeMounts:
        - name: envoy-config
          mountPath: /config
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
      containers:
      - name: envoy
        image: "soloio/envoy:v0.1.6-111"
        imagePullPolicy: IfNotPresent
        ports: 
        - containerPort: 8080
          name: http
        - containerPort: 8443 
          name: https
        - containerPort: 19000
          name: admin
        command: ["envoy"]
        args: ["-c", "/config/envoy.yaml", "--v2-config-only"]
        volumeMounts:
        - name: envoy-config
          mountPath: /config
      volumes:
      - name: envoy-config
        configMap:
          name: ingress-config 
---
# Source: gloo/templates/k8s-ingress-deployment.yaml

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ingress-controller
  namespace: gloo-system
  labels:
    gloo: ingress-controller
spec:
  selector:
    matchLabels:
      gloo: ingress-controller
  replicas: 1
  template:
    metadata:
      labels:
        gloo: ingress-controller
    spec:
      containers:
      - image: "soloio/gloo-ingress-controller:90f2b21"
        imagePullPolicy: IfNotPresent
        name: ingress-controller
        env:
        - name: DEBUG
          value: "1"
        - name: GRPC_TRACE
          value: all
        command: ["/gloo-ingress-controller"]
        args:
        - "--service=envoy"
        - "--syncperiod=30m"
        - "--storage.type=kube"
        - "--kube.namespace=gloo-system"

---
# Source: gloo/templates/sd-deployment.yaml

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    gloo: k8s-service-discovery
  name: service-discovery
  namespace: gloo-system
spec:
  selector:
    matchLabels:
      gloo: k8s-service-discovery
  replicas: 1
  template:
    metadata:
      labels:
        gloo: k8s-service-discovery
    spec:
      containers:
      - image: soloio/gloo-k8s-service-discovery:12b4753
        imagePullPolicy: IfNotPresent
        name: k8s-service-discovery
        env:
        - name: GRPC_TRACE
          value: "all"
        - name: DEBUG
          value: "1"
        args:
        - "--storage.type=kube"
        - "--syncperiod=30m"
        - "--kube.namespace=gloo-system"

